version: '3'
services:
  ruby:
    image: ruby:latest
    command: bash -c 'gem install aws-sdk-core aws-sdk-ssoadmin && ruby test.rb'
    working_dir: /usr/app/
    volumes:
      - ./:/usr/app/
    env_file:
      - dev.env